---
- hosts: tiuraniemi.io
  become: true
  become_user: root
  tasks:
      - name: Install pip3
        apt: 
            name: python3-pip
      - name: Install virtualenv
        pip:
            name: virtualenv
