name: Build and Deploy
on:
    push:
        branches:
            - main
        paths-ignore:
            - 'deploy/hosts.yml'
            - 'deploy/upgrade.yml'
            - 'deploy/setup_services.yml'
            - 'deploy/services/*'
            - '**.md'
jobs:
    build:
        name: Build ande deploy site
        runs-on: ubuntu-latest
        steps:
            - name: Remove nginx for libgd problems
              run: sudo apt-get remove nginx
            - name: Remove too new libgd
              run: sudo apt-get remove libgd3
            - name: Add correct libgd
              run: sudo apt-get install -yq libgd-dev
            - name: Checkout
              uses: actions/checkout@v3
            - name: Setup Node
              uses: actions/setup-node@v2
              with:
                  node-version: '16.x'
                  cache: 'npm'
            - run: npm install
            - run: npm run build
            - name: Deploy site to live
              uses: dawidd6/action-ansible-playbook@v2
              with:
                  directory: deploy
                  playbook: sync_site.yml
                  key: ${{ secrets.SSH_PRIVATE_KEY }}
                  known_hosts: ${{ secrets.SSH_KNOWN_HOSTS }}
                  options: --inventory hosts.yml
