name: Build and Deploy
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Build ande deploy site
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          cache: 'npm'
      - run: npm install
      - run: npm run build
