name: Upgrade
on:
    # schedule:
    #     - cron: '00 14 * * *'
    push:
        branches:
            - main
jobs:
    upgrade:
        name: Upgrade the server via Ansible
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Run ansible
              uses: dawidd6/action-ansible-playbook@v2
              with:
                  directory: deploy
                  playbook: upgrade.yml
                  options: --inventory hosts
                  key: ${{secrets.SSH_PRIVATE_KEY}}
                  known_hosts: ${{secrets.SSH_KNOWN_HOSTS}}
